name: miru_anime
description: App for viewing anime.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.6.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  dio: ^5.1.1
  html: ^0.15.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  font_awesome_flutter: ^10.0.0
  cached_network_image: ^3.2.0
  card_swiper: ^3.0.1
  photo_view: ^0.15.0
  fluttertoast: ^8.0.8
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  share_plus: ^10.1.0
  better_player: ^0.0.84
  flutter_svg: ^2.0.4
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  oauth2_client: ^3.2.1
  http: ^1.2.2
  encrypt: ^5.0.1
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  objectbox_generator: any
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: false
  ios: true
  image_path:  "assets/ic_launcher_square.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/genres/
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_light.ttf
          weight: 300
        - asset: assets/fonts/montserrat_regular.ttf
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat_semibold.ttf
          weight: 600

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
